version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourapp
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4001
      - COMMON_JWT_SECRET=${COMMON_JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - '4001:4001'
    depends_on:
      - db
volumes:
  db_data:
