version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourapp
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4001
      - COMMON_JWT_SECRET=${COMMON_JWT_SECRET}
    ports:
      - '4001:4001'
    depends_on:
      - db
  bff:
    build: ./bff
    env_file: ./.env
    environment:
      - BFF_PORT=4000
      - BACKEND_GRAPHQL_URL=http://backend:4001/graphql
    ports:
      - '4000:4000'
    depends_on:
      - backend
volumes:
  db_data:
